import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import clsx from "clsx";
import Header from '@/components/layout/Header'
import Provider from '@/components/layout/Provider'
import WindowResponsive from '@/components/layout/WindowResponsive';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ngvcanh site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ fontSize: "16px" }}>
      <body className={clsx(inter.className)}>
        <Provider>
          <WindowResponsive />
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
